version: "3"  
services:
  db:
    image: postgres:alpine
    container_name: "wp_db"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=web_panel 
  db_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=landofdevs@protonmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    container_name: "wp_db_admin"
    depends_on: 
      - db
    volumes:
      - ./config/pgadmin.json:/pgadmin4/servers.json
  web:
    image: nginx:latest
    container_name: "wp_web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - db_admin
      - wp_nest
      - wp_vue3
      - wp_laravel
  wp_nest:
    container_name: wp_nest
    image: node:alpine
    volumes:
      - ./backend/nestjs:/project
    ports:
      - 9001:9001
    command: cd project && npm install && npm run start:dev
    env_file:
      - .env
    depends_on:
      - db

  wp_laravel:
    tty: true
    container_name: wp_laravel
    image: docker.io/bitnami/laravel:8
    volumes:
      - ./backend/laravel:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 9003-9003

  wp_vue3:
    container_name: wp_vue3
    image: node:alpine
    volumes:
      - ./frontend:/project
    ports:
      - 8000:8000
    command: cd project && npm install && npm run start:dev
    env_file:
      - .env

  wp_go:
    container_name: wp_go
    image: golang:alpine
    volumes:
      - ./backend/go:/project
    ports:
      - 9002:9002
    command: cd project && go mod download && go run app.go
    depends_on: 
      - dḅ̣
