version: "3"  
services:
  db:
    image: postgres:alpine
    container_name: "wp_db"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=web_panel 
  db_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=landofdevs@protonmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    container_name: "wp_db_admin"
    depends_on: 
      - db
  web:
    image: nginx:latest
    container_name: "wp_web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - db_admin
