version: "3"  
services:
  wp_db:
    image: postgres:alpine
    container_name: "wp_db"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=web_panel 
  db_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=landofdevs@protonmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_DISABLE_POSTFIX=1
      - GUNICORN_ACCESS_LOGFILE=/dev/null
    container_name: "wp_db_admin"
    depends_on: 
      - wp_db
    volumes:
      - ./config/pgadmin.json:/pgadmin4/servers.json
  web:
    image: nginx:latest
    container_name: "wp_web"
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/app_data
    depends_on:
      - db_admin
      - wp_nest
      - wp_vue3
      - wp_laravel
      - wp_go

  wp_nest:
    container_name: "wp_nest"
    image: node:alpine
    volumes:
      - ./backend/nestjs:/home/node/app/
      - ./data:/app_data
      - ./config/private/${ENV:-dev}:/private/
      - ./config/startnode.sh:/startnode.sh:ro
    working_dir: /home/node/app/
    command: sh /startnode.sh
    env_file:
      - .env
      - config/private/${ENV:-dev}/secrets.env
      - config/private/${ENV:-dev}/super-secrets.env
    depends_on:
      - wp_db

  wp_laravel:
    tty: true
    container_name: "wp_laravel"
    build: ./config/docker/laravel
    entrypoint: sudo -E sh /pre-app-entrypoint.sh
    volumes:
      - ./backend/laravel:/app
      - ./data:/app_data
      - ./config/private/${ENV:-dev}:/private/
      - ./config/startlaravel.sh:/pre-app-entrypoint.sh:ro
    env_file:
      - .env
      - config/private/${ENV:-dev}/secrets.env
    depends_on:
      - wp_db
      - wp_go

  wp_vue3:
    container_name: "wp_vue3"
    image: node:14-alpine
    volumes:
      - ./frontend:/home/node/app/
      - ./data:/app_data
      - ./config/startnode.sh:/startnode.sh:ro
    working_dir: /home/node/app/
    command: sh /startnode.sh

  wp_go:
    container_name: "wp_go"
    image: golang:alpine
    volumes:
      - ./backend/go:/project
      - ./data:/app_data
      - ./config/private/${ENV:-dev}:/private/
      - ./config/startgo.sh:/startgo.sh:ro
    env_file:
      - .env
      - config/private/${ENV:-dev}/secrets.env
      - config/private/${ENV:-dev}/super-secrets.env
    command: sh /startgo.sh
    depends_on: 
      - wp_db
